version: '3'

services:
  otus-sn-backend:
    container_name: otus-sn-backend
    build: backend
    ports: 
      - 8000:8000
    restart: always
    environment:
      DB_CONN: host=otus-sn-database dbname=otus-sn user=otus-sn password=otus-sn

  otus-sn-database:
    container_name: otus-sn-database
    image: postgres:16
    ports: 
      - 5432:5432
    restart: always
    command: -c 'max_connections=200'
    environment: 
      POSTGRES_DB: otus-sn
      POSTGRES_USER: otus-sn
      POSTGRES_PASSWORD: otus-sn
    volumes: 
      - otus-sn-database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otus-sn"]
      interval: 5s
      timeout: 5s
      retries: 5

  otus-sn-database-pgmigrate:
    container_name: otus-sn-database-pgmigrate
    build:
      context: database
      dockerfile: pgmigrate.Dockerfile
    depends_on:
      otus-sn-database:
        condition: service_healthy
    environment: 
      DB_CONN: host=otus-sn-database dbname=otus-sn user=otus-sn password=otus-sn

volumes:
  otus-sn-database-data:
