version: '3'

services:
  otus-sn-database:
    container_name: otus-sn-database
    image: postgres:16
    ports: 
      - 5432:5432
    restart: always
    environment: 
      POSTGRES_DB: otus-sn
      POSTGRES_USER: otus-sn
      POSTGRES_PASSWORD: otus-sn
    volumes: 
      - /opt/otus-sn/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otus-sn"]
      interval: 5s
      timeout: 5s
      retries: 5

  otus-sn-database-pgmigrate:
    container_name: otus-sn-database-pgmigrate
    build:
      dockerfile: pgmigrate.Dockerfile
    depends_on:
      otus-sn-database:
        condition: service_healthy
    environment: 
      POSTGRES_CONNECTION_STRING: host=otus-sn-database dbname=otus-sn user=otus-sn password=otus-sn
